### ISSUE TITLE
can't send extrinsics `Unable to query nonce`

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#75]
```
2022-02-27 11:43:20        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
m	@	polkadot.02.af3d2814.js:1
Error: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
    at c._checkError (polkadot.01.d9777b89.js:1:104630)
    at c.decodeResponse (polkadot.01.d9777b89.js:1:104269)
    at z.value (polkadot.01.d9777b89.js:1:110316)
    at WebSocket.value (polkadot.01.d9777b89.js:1:110129)
polkadot.02.af3d2814.js:1 2022-02-27 11:43:22        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
m	@	polkadot.02.af3d2814.js:1
Error: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
    at c._checkError (polkadot.01.d9777b89.js:1:104630)
    at c.decodeResponse (polkadot.01.d9777b89.js:1:104269)
    at z.value (polkadot.01.d9777b89.js:1:110316)
    at WebSocket.value (polkadot.01.d9777b89.js:1:110129)
polkadot.02.af3d2814.js:1 2022-02-27 11:43:26        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
m	@	polkadot.02.af3d2814.js:1
Error: 1: Unable to query dispatch info.: Application, Execution, Other, Exported method TransactionPaymentApi_query_info is not found
    at c._checkError (polkadot.01.d9777b89.js:1:104630)
    at c.decodeResponse (polkadot.01.d9777b89.js:1:104269)
    at z.value (polkadot.01.d9777b89.js:1:110316)
    at WebSocket.value (polkadot.01.d9777b89.js:1:110129)
polkadot.02.af3d2814.js:1 2022-02-27 11:43:28        RPC-CORE: accountNextIndex(accountId: AccountId): Index:: 1: Unable to query nonce.: Application, Execution, Other, Exported method AccountNonceApi_account_nonce is not found
m	@	polkadot.02.af3d2814.js:1
main.190ebc16.js:19 signAndSend: error: Error: 1: Unable to query nonce.: Application, Execution, Other, Exported method AccountNonceApi_account_nonce is not found
    at c._checkError (polkadot.01.d9777b89.js:1:104630)
    at c.decodeResponse (polkadot.01.d9777b89.js:1:104269)
    at z.value (polkadot.01.d9777b89.js:1:110316)
    at WebSocket.value (polkadot.01.d9777b89.js:1:110129)
﻿```

**Comment by brenzi** [comment]
the wasm runtime with `spec_version = 0` is pretty old (2021-07-13)
* wasm: based on https://github.com/integritee-network/parachain/commit/71e8c0653403068bea5866ba76185e1933fb30fd which depends on https://github.com/paritytech/substrate/commit/9c572625f6557dfdb19f47474369a0327d51dfbc
* collator based on polkadot-0.9.16

**Comment by brenzi** [comment]
we may try to fix this by composing extrinsics manually, with substrate-api-client compose_offline_extrinsic where the nonce can be specified manually

**Comment by brenzi** [comment]
I was able to send an extrinsic with an old version of substrate-api-client based on V13 metadata. We can compose a setCode extrinsic like that and fix the chain

just replace sudoer with real seed here:

https://github.com/scs/substrate-api-client/pull/215

But before we can do `setCode`, we should add a generic example for that: 

https://github.com/scs/substrate-api-client/issues/217

**Comment by brenzi** [comment]
fixed by reverting api-client to matadata V13 commit:

use https://github.com/scs/substrate-api-client/pull/219

1. replace signer seed in example with kusama para sudo
2. replace wasm with https://github.com/integritee-network/parachain/releases/download/1.4.12/shell_runtime-v2.compact.compressed.wasm

```
./target/release/examples/example_setcode_extrinsic -u wss://kusama.api.integritee.network -p 443
Interacting with node on wss://kusama.api.integritee.network:443

signer account: 5EqGFRTN3m2kLpoaThANra5REs5C7B2rfLmmZv2nbJsxaTe1
[+] Transaction got included. Hash: Some(0xc58376aea5611fb1d8e8ac1b06168576348b6823d42a0823c4103c52a63e9a33)
```

extrinsic success, check kusama relaychain for upgrading para 2015 (takes ~1h)
